export const LOAD_BILL_DATA = 'LOAD_BILL_DATA';
export const DELETE_BILL= 'DELETE_BILL';
// export const LOAD_BILL_DATA_SUCCESS = 'LOAD_BILL_DATA_SUCCESS';
// export const LOAD_BILL_DATA_FAILURE = 'LOAD_BILL_DATA_FAILURE';

// export const CREATE_BILL_START = 'CREATE_BILL_START';
// export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS';
// export const CREATE_BILL_FAILURE = 'CREATE_BILL_FAILURE';

// export const UPDATE_BILL_START = 'UPDATE_BILL_START';
// export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';
// export const UPDATE_BILL_FAILURE = 'UPDATE_BILL_FAILURE';

// export const DELETE_BILL_START = 'DELETE_BILL_START';
// export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
// export const DELETE_BILL_FAILURE = 'DELETE_BILL_FAILURE';
